### ISSUE TITLE
Exception thrown when using ZF2.2.1, DoctrineORMModule 0.7.0 and CLI script

### ISSUE THREAD

**Issue by localheinz** [doctrine/DoctrineORMModule#238]
After updating ZF2 to 2.2.1 - using DoctrineORMModule 0.7.0 - and issuing the command

```
$ ./vendor/doctrine-module orm:generate-proxies
```

an uncaught exception is thrown:

```
PHP Fatal error:  Uncaught exception 'Zend\Mvc\Router\Exception\RuntimeException' with message 'Given route does not implement Console route interface' in /example.com/vendor/zendframework/zendframework/library/Zend/Mvc/Router/Console/SimpleRouteStack.php:81
Stack trace:
#0 /example.com/vendor/zendframework/zendframework/library/Zend/Mvc/Router/Console/SimpleRouteStack.php(51): Zend\Mvc\Router\Console\SimpleRouteStack->routeFromArray(Array)
#1 /example.com/vendor/zendframework/zendframework/library/Zend/Mvc/Router/SimpleRouteStack.php(140): Zend\Mvc\Router\Console\SimpleRouteStack->addRoute('doctrine_orm_mo...', Array)
#2 /example.com/vendor/zendframework/zendframework/library/Zend/Mvc/Router/SimpleRouteStack.php(84): Zend\Mvc\Router\SimpleRouteStack->addRoutes(Array)
#3 [internal function]: Zend\Mvc\Router\SimpleRouteStack::factory(Array)
#4 /Users/am/Sites/public/carzapp/beta.carzapp.dev in /example.com/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 860

Fatal error: Uncaught exception 'Zend\Mvc\Router\Exception\RuntimeException' with message 'Given route does not implement Console route interface' in /example.com/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 860

Zend\Mvc\Router\Exception\RuntimeException: Given route does not implement Console route interface in /example.com/vendor/zendframework/zendframework/library/Zend/Mvc/Router/Console/SimpleRouteStack.php on line 81

Call Stack:
    0.0002     226528   1. {main}() /example.com/script/doctrine-module.php:0
    0.0026     433232   2. include('/example.com/vendor/doctrine/doctrine-module/bin/doctrine-module.php') /example.com/script/doctrine-module.php:29
    0.0035     499768   3. Zend\Mvc\Application::init() /example.com/vendor/doctrine/doctrine-module/bin/doctrine-module.php:46
    0.0491    4112288   4. Zend\Mvc\Application->bootstrap() /example.com/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php:254
    0.0527    4421472   5. Zend\ServiceManager\ServiceManager->get() /example.com/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php:153
    0.0527    4422008   6. Zend\ServiceManager\ServiceManager->create() /example.com/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php:481
    0.0527    4422008   7. Zend\ServiceManager\ServiceManager->doCreate() /example.com/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php:557
    0.0527    4422056   8. Zend\ServiceManager\ServiceManager->createFromFactory() /example.com/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php:598
    0.0529    4432056   9. Zend\ServiceManager\ServiceManager->createServiceViaCallback() /example.com/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php:983
    0.0529    4432384  10. call_user_func() /example.com/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php:853
    0.0529    4432424  11. Zend\Mvc\Service\RouterFactory->createService() /example.com/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php:853
    0.0529    4433336  12. call_user_func() /example.com/vendor/zendframework/zendframework/library/Zend/Mvc/Service/RouterFactory.php:65
    0.0536    4509384  13. Zend\Mvc\Router\SimpleRouteStack::factory() /example.com/vendor/zendframework/zendframework/library/Zend/Mvc/Service/RouterFactory.php:65
    0.0540    4538712  14. Zend\Mvc\Router\SimpleRouteStack->addRoutes() /example.com/vendor/zendframework/zendframework/library/Zend/Mvc/Router/SimpleRouteStack.php:84
    0.0540    4539376  15. Zend\Mvc\Router\Console\SimpleRouteStack->addRoute() /example.com/vendor/zendframework/zendframework/library/Zend/Mvc/Router/SimpleRouteStack.php:140
    0.0540    4539480  16. Zend\Mvc\Router\Console\SimpleRouteStack->routeFromArray() /example.com/vendor/zendframework/zendframework/library/Zend/Mvc/Router/Console/SimpleRouteStack.php:51

Zend\ServiceManager\Exception\ServiceNotCreatedException: An exception was raised while creating "Router"; no instance returned in /example.com/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 860

Call Stack:
    0.0002     226528   1. {main}() /example.com/script/doctrine-module.php:0
    0.0026     433232   2. include('/example.com/vendor/doctrine/doctrine-module/bin/doctrine-module.php') /example.com/script/doctrine-module.php:29
    0.0035     499768   3. Zend\Mvc\Application::init() /example.com/vendor/doctrine/doctrine-module/bin/doctrine-module.php:46
    0.0491    4112288   4. Zend\Mvc\Application->bootstrap() /example.com/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php:254
    0.0527    4421472   5. Zend\ServiceManager\ServiceManager->get() /example.com/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php:153
    0.0527    4422008   6. Zend\ServiceManager\ServiceManager->create() /example.com/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php:481
    0.0527    4422008   7. Zend\ServiceManager\ServiceManager->doCreate() /example.com/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php:557
    0.0527    4422056   8. Zend\ServiceManager\ServiceManager->createFromFactory() /example.com/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php:598
    0.0529    4432056   9. Zend\ServiceManager\ServiceManager->createServiceViaCallback() /example.com/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php:983
```
